/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abogados: typeof import('./src/components/abogados.vue')['default']
    CrudCardData: typeof import('./src/components/commons/CrudCardData.vue')['default']
    CrudControls: typeof import('./src/components/commons/CrudControls.vue')['default']
    CrudDeleteModal: typeof import('./src/components/commons/CrudDeleteModal.vue')['default']
    CrudEditModal: typeof import('./src/components/commons/CrudEditModal.vue')['default']
    CrudTable: typeof import('./src/components/commons/CrudTable.vue')['default']
    CrudTableData: typeof import('./src/components/commons/CrudTableData.vue')['default']
    Docentes: typeof import('./src/components/docentes.vue')['default']
    Funcpublic: typeof import('./src/components/funcpublic.vue')['default']
    FuncPublic: typeof import('./src/components/FuncPublic.vue')['default']
    General: typeof import('./src/components/general.vue')['default']
    Itaipu: typeof import('./src/components/itaipu.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
